### ISSUE TITLE
[Enhancement] Add a paste button for 2FA Code

### ISSUE THREAD

**Issue by SnowJuli** [juliand665/Recon-Bolt#11]
Hello,

It would be nice to have a button which pastes your clipboard into the 2FA Field when logging in. It's a bit annoying to manually type it in :D 

P.S.: Maybe add an issue template with [this](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) or reach out to me if you need any help. It is a very cool project you made here!

Cheers.
Juli

**Comment by juliand665** [comment]
Thanks for the suggestions! I think templates aren't really necessary until the issue system sees higher levels of activity—I haven't received a single bug report on here, so I don't know how well users will or won't know to provide the necessary info lol

As for pasting, is selecting the code in the email and copying it really faster than just typing it out real quick? I would have never thought to do that.

**Comment by yungbeatz** [comment]
I just personally think it would increase the user-friendliness, especially with the auto paste feature, which I think exists since iOS 14? 
Furthermore, I would implement that feature and if others don't like auto pasting, they can just type it out.
![Screenshot 2022-10-17 111821](https://user-images.githubusercontent.com/56764505/196139863-74c8650f-b10b-464a-a45c-9581505ccfe3.png)

**Comment by juliand665** [comment]
Idk, to me selecting and copying the 6 digits seems like a _lot_ more work than simply… memorizing them real quick? Especially with the new app switcher interface since notched iPhones letting you fluidly peek at the code in the mail app without really leaving your current context. But perhaps others have a harder time with that? Hmm.

**Comment by yungbeatz** [comment]
You got a good point there, problem is iPhones without notch don't have that. Since the mass uses iPhones with a notch it wouldn't be much of a problem but I'd say thinking about the OG Home Button peeps would be a good idea too. After all at the end the enduser can decide wherever if its going to copy and then paste or just memorize it.

**Comment by juliand665** [comment]
Ok, considering I seem to have fixed the issue of sessions expiring too often, you almost never have to enter a 2FA code, so I've decided this isn't worth the effort :p
