### ISSUE TITLE
Weapon loadout not updated

### ISSUE THREAD

**Issue by SjorsSchijff** [juliand665/Recon-Bolt#13]
Given:

1. I have multiple accounts added

When:

1. Opening the Live tab
2. Opening the details view for my weapon loadout
3. Selecting the settings tab
4. Switching to a different account
5. Navigating back to the live tab

Expected outcome:

1. The weapon loadout is adjusted for the currently selected account

Actual outcome:

1. The weapon loadout remains the same

I like numbers

Kind regards

PS: How can I get Pro currently? Would like to support development

**Comment by juliand665** [comment]
Thanks for the detailed report! I'm not sure how easy this is to fix in a general way, rather than just building in special handling for the loadout screen, but it's certainly something worth investigating, especially if I end up adding a more detailed store view or something.

PS: you'll have to wait for it to release on the App Store! Only then will Apple actually let you send me money ;)

**Comment by SjorsSchijff** [comment]
This might not be be the most elegant solution (I dont have a lot of SwiftUI experience and familiarity with your codebase), but it gets the job done.

Do with it as you seem fit ;-)

**Comment by juliand665** [comment]
Ended up addressed in https://github.com/juliand665/Recon-Bolt/commit/19dabe29e8bf3c636e7f63094b29fa564e49c9eb (from #15)
