### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by MoonDeityy** [juliand665/Recon-Bolt#16]
Can I be banned for this app?

**Comment by ConnorDoesDev** [comment]
no

**Comment by juliand665** [comment]
For a more official response, Riot haven't made an official statement on it, but I haven't heard of anyone getting banned for it, and I'm pretty sure they'd contact me first if they wanted me to take it down or make changes. It's easier for them to just silently accept it than to take an official position, because that inevitably creates a negative reaction from some group of people.
