### ISSUE TITLE
Is there a way to get it for android?

### ISSUE THREAD

**Issue by MaxiscooI** [juliand665/Recon-Bolt#44]
Is there a way to download it on android mabye with a apk?

**Comment by ConnorDoesDev** [comment]
No

**Comment by juliand665** [comment]
Let me quickly copy paste from the FAQ on the Discord server:

> **Why not Android?**
This app is a passion project that I only work on because it motivates me. A large part of that motivation comes from using the SwiftUI framework, which is a joy to work with, but only available on Apple platforms. In order to port to Android, I would essentially have to rewrite the entire app from scratch, and it would take hundreds of hours. I have no motivation for that, plus I don't even have a single Android device in the house. Maybe this app will inform your next phone purchase ;)
> 
> There is a similar app for Android, **Statics for Valorant**: https://discord.gg/jwfJUQMPP7. It recently received an update to let you participate in Agent Select, among other features!
> 
> **Ok, but PC?**
Also not happening—the true value of the app to me lies in the power to interact with Valorant (pick agents, view match history, etc.) from afar, and so a PC version would kinda defeat the point.
